-- Tạo bảng
CREATE TABLE NHANVIEN (
    MANV INT,
    HOTEN NVARCHAR(50),
    LUONG MONEY
);

CREATE TABLE DUAN (
    MADA INT,
    TENDUAN VARCHAR(50)
);

-- Thêm dữ liệu
INSERT INTO NHANVIEN (MANV, HOTEN, LUONG) VALUES (1, N'Nguyễn Văn A', 15000000);
INSERT INTO NHANVIEN (MANV, HOTEN, LUONG) VALUES (2, N'Trần Thị B', 12000000);

INSERT INTO DUAN (MADA, TENDUAN) VALUES (101, 'Du an E-Learning');
